### PR TITLE
update shard and rclone sizes

### PR DESCRIPTION
**Pull request by gotjoshua**
and use intl date format

### CODE REVIEW

**Comment by Pemidi** [comment]
Is anybody here?
What is the point of ignoring PRs?

**Comment by gupadhyaya** [comment]
> Is anybody here?
> What is the point of ignoring PRs?

yes we are here. are the numbers still accurate?

**Comment by gotjoshua** [comment]
> are the numbers still accurate?

thats a bit of an odd question....

The numbers were (and thus still are) accurate as of  8 Dec 2020
...
which is quite a while ago, so i guess the date and numbers need to be updated.

I will not do this as I am no longer running a node.

**Comment by givp** [comment]
This has been fixed in a different PR. Closing.

**Pull request closed without merging**
