### PR TITLE
Updated storage/bandwith requirements

### PR DESCRIPTION
**Pull request by crypto-gainz**

### CODE REVIEW

**Comment by crypto-gainz** [comment]
Anyone here? @givp let me know if this style is ok for you!

**Comment by givp** [comment]
Sorry @crypto-gainz ! Please assign the PR to me next time so I get notified. Reviewing now.

**Comment by givp** [comment]
Looks great. Thank you!

**Comment by crypto-gainz** [comment]
Got it, next time I will assign it to you directly. I'll keep updating stuff now that I know the style is good.

**Pull request merged**
